---

- name: Install Docker and Verify
  hosts: labs_linux
  become: true
  vars:
    uninstall_packages: [docker.io, docker-compose, docker-doc, podman-docker, containerd]
    pre_setup_packages: [ca-certificates, curl, gnupg]
    docker_packages: [docker-ce, docker-ce-cli, containerd.io, docker-buildx-plugin, docker-compose-plugin]

  tasks:
    - name: (1/14) Test Reacheability
      ansible.builtin.ping:

    - name: (2/14) Update Cache
      ansible.builtin.apt:
        update_cache: true
        autoclean: true

    - name: (3/14) Upgrade All the Packages to the latest
      ansible.builtin.apt:
        upgrade: "full"

    - name: (4/14) Remove (if available) conflicting packages
      ansible.builtin.apt:
        name: '{{ uninstall_packages }}'
        state: absent

    - name: (5/14) Update Cache
      ansible.builtin.apt:
        update_cache: true
        autoclean: true

    - name: (6/14) Install packages to allow apt to use a repository over HTTPS
      ansible.builtin.apt:
        name: '{{ pre_setup_packages }}'

    # https://github.com/modem7/Ansible/blob/master/tasks/docker_install.yaml
    - name: (7/14) Remove gpg keys if they exist # otherwise GPG doesn't run if file already exists
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /usr/share/keyrings/docker-archive-keyring.gpg
        - /usr/share/keyrings/docker-archive-keyring.gpg_armored

    # https://github.com/modem7/Ansible/blob/master/tasks/docker_install.yaml
    - name: (8/14) Download Docker gpg key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.gpg_armored
        mode: '0755'
        checksum: sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570 # curl -sL https://download.docker.com/linux/ubuntu/gpg|sha256sum

    # https://github.com/modem7/Ansible/blob/master/tasks/docker_install.yaml
    - name: (9/14) De-Armor Docker GPG key
      ansible.builtin.shell: gpg --dearmor < /usr/share/keyrings/docker-archive-keyring.gpg_armored > /usr/share/keyrings/docker-archive-keyring.gpg
      no_log: true
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg

    # https://github.com/modem7/Ansible/blob/master/tasks/docker_install.yaml
    # https://git.deuxfleurs.fr/Deuxfleurs/infrastructure/src/commit/7852eef5a6d0eefc5914f178549f6845857a5c49/os/config/roles/common/tasks/docker.yml
    - name: (10/14) Add Docker's repository to APT sources list
      ansible.builtin.apt_repository:
        repo: >
          deb [arch={{ architecture_map[ansible_architecture] }}
          signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        state: present
        update_cache: true
      vars:
        architecture_map:
          "x86_64": "amd64"
          "aarch64": "arm64"
          "aarch": "arm64"
          "armhf": "armhf"
          "armv7l": "armhf"

    - name: (11/14) Install Docker Engine
      ansible.builtin.apt:
        name: '{{ docker_packages }}'

    # This is for lxc containers because it seems like some doesn't come with pip or requests package. Because of that the last step fails.
    - name: (12/14) Install pip3 if unavailable
      ansible.builtin.apt:
        name:
          - python3-pip
        state: present

    - name: (13/14) Install 'requests' if unavailable
      ansible.builtin.pip:
        name:
          - requests
      tags:
        - test

    - name: (14/14) Verify Docker Engine installation is successful
      community.docker.docker_container:
        name: hello-world
        image: hello-world
        auto_remove: true
        state: started
