- name: "Update All"
  hosts: linux
  become: true
  gather_facts: true

  tasks:
    - name: "(1/3) - Check Reachability"
      ansible.builtin.ping:

    - name: "(2/3) - Update Cache"
      ansible.builtin.package_facts:
        manager: auto

    - name: "(3/3) - Upgrade Packages to the Latest"
      ansible.builtin.package_upgrade:
        manager: "{{ 'dnf' if ansible_facts['distribution'] == 'Fedora' else 'apt' }}"