---

- name: "Update All"
  hosts: linux
  become: true

  tasks:
    - name: "(1/3) - Check Reachability"
      ansible.builtin.ping:

    - name: "(2/3) - Update Cache"
      ansible.builtin.apt:
        update_cache: true
        autoclean: true

    - name: "(3/3) - Upgrade Packages to the Latest"
      ansible.builtin.apt:
        upgrade: "full"
