---

- name: "Update All"
  hosts: linux
  become: true

  tasks:
    - name: "Check Reachability"
      ansible.builtin.ping:

    - name: "Update APT Cache"
      ansible.builtin.apt:
        update_cache: true
        autoclean: true
      when: ansible_facts['os_family'] == 'Debian'

    - name: "Upgrade APT Packages to the Latest"
      ansible.builtin.apt:
        upgrade: "full"
      when: ansible_facts['os_family'] == 'Debian'

    - name: "Upgrade DNF Packages"
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == 'RedHat'
